import * as fs   from 'fs';
import * as path from 'path';
import { ClassInfo, ClassMap, DirectoryConfig, GenerateResult } from './types';

// ─── PHP Parsing ─────────────────────────────────────────────────────────────

function extractClassInfo(content: string): ClassInfo | null {
    const nsMatch    = content.match(/^namespace\s+([^;{]+)[;{]/m);
    const classMatch = content.match(/^(?:abstract\s+)?(?:class|interface|trait|enum)\s+(\w+)/m);

    if (!nsMatch || !classMatch) return null;

    return {
        namespace: nsMatch[1].trim(),
        className: classMatch[1].trim(),
    };
}

// ─── Directory Scanner ───────────────────────────────────────────────────────

function scanDir(
    dir:         string,
    basePath:    string, // The directory containing the classmap file
    classMap:    ClassMap,
    skipFile:    string,
): void {
    let entries: fs.Dirent[];

    try {
        entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
        return;
    }

    for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);

        if (entry.isDirectory()) {
            scanDir(fullPath, basePath, classMap, skipFile);
            continue;
        }

        if (!entry.name.endsWith('.php')) continue;
        if (fullPath === skipFile)        continue;

        let content: string;
        try {
            content = fs.readFileSync(fullPath, 'utf8');
        } catch {
            continue;
        }

        const info = extractClassInfo(content);
        if (!info) continue;

        const fullClass = `${info.namespace}\\${info.className}`;
        
        // FIX: Make path relative to the OUTPUT file's directory
        // This ensures PHP's __DIR__ . $path works correctly.
        const relativePath = path.relative(basePath, fullPath)
            .split(path.sep)
            .join('/');

        classMap[fullClass] = relativePath;
    }
}

// ─── Writer ──────────────────────────────────────────────────────────────────

function writeClassmapFile(classMap: ClassMap, outputPath: string): void {
    const entries = Object.entries(classMap)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([k, v]) => `    '${k}' => '${v}',`)
        .join('\n');

    const timestamp = new Date().toISOString();
    const php = [
        '<?php',
        `// Auto-generated by WP Classmap: Lightning Fast Autoloading — ${timestamp}`,
        '// Do not edit manually.',
        'return array(',
        entries,
        ');',
        '',
    ].join('\n');

    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    fs.writeFileSync(outputPath, php, 'utf8');
}

// ─── Public API ──────────────────────────────────────────────────────────────
export function generateClassmap(
    includesDir: string,
    outputFile:  string,
): GenerateResult {
    const scanPath   = path.resolve(includesDir);
    const outputPath = path.resolve(outputFile);
    const outputDir  = path.dirname(outputPath); // Base for relative paths

    if (!fs.existsSync(scanPath)) {
        throw new Error(`Directory not found: ${scanPath}`);
    }

    const classMap: ClassMap = {};
    
    // We pass outputDir so paths in the PHP file are relative to the file itself
    scanDir(scanPath, outputDir, classMap, outputPath);
    
    writeClassmapFile(classMap, outputPath);

    return { 
        includesDir: path.basename(scanPath), 
        count: Object.keys(classMap).length, 
        outputPath 
    };
}

export function generateAllClassmaps(
    directories: DirectoryConfig[],
): GenerateResult[] {
    return directories.map(({ includesDir, outputFile }) => {
        try {
            return generateClassmap(includesDir, outputFile);
        } catch (err) {
            return {
                includesDir,
                count:      0,
                outputPath: outputFile,
                error:      (err as Error).message,
            };
        }
    });
}