import * as fs   from 'fs';
import * as path from 'path';
import { ClassInfo, ClassMap, DirectoryConfig, GenerateResult, Warning } from './types';

// ─── PHP Parsing ─────────────────────────────────────────────────────────────

function extractClassInfo(content: string): ClassInfo | null {
    const nsMatch    = content.match(/^namespace\s+([^;{\s]+)/m);
    const classMatch = content.match(/^(?:(?:final|abstract|readonly)\s+)*(?:class|interface|trait|enum)\s+(\w+)/m);

    if (!nsMatch || !classMatch) return null;

    return {
        namespace: nsMatch[1].trim(),
        className: classMatch[1].trim(),
    };
}

/**
 * Count how many class-like declarations exist in a file.
 * Used to warn when more than one is found.
 */
function countClassDeclarations(content: string): number {
    const matches = content.match(
        /^(?:(?:final|abstract|readonly)\s+)*(?:class|interface|trait|enum)\s+\w+/mg
    );
    return matches ? matches.length : 0;
}

// ─── Default Exclusions ──────────────────────────────────────────────────────

const DEFAULT_EXCLUDE: ReadonlySet<string> = new Set([
    'vendor',
    'node_modules',
    '.git',
]);

// ─── Directory Scanner ───────────────────────────────────────────────────────

function scanDir(
    dir:      string,
    basePath: string,
    classMap: ClassMap,
    skipFile: string,
    exclude:  ReadonlySet<string>,
    warnings: Warning[],
): void {
    let entries: fs.Dirent[];

    try {
        entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
        return;
    }

    for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);

        if (entry.isDirectory()) {
            // Skip excluded directory names
            if (exclude.has(entry.name)) continue;
            scanDir(fullPath, basePath, classMap, skipFile, exclude, warnings);
            continue;
        }

        if (!entry.name.endsWith('.php')) continue;
        if (fullPath === skipFile)        continue;

        let content: string;
        try {
            content = fs.readFileSync(fullPath, 'utf8');
        } catch {
            continue;
        }

        // ── Warning: multiple classes in one file ──
        const classCount = countClassDeclarations(content);
        if (classCount > 1) {
            warnings.push({
                type:    'multiple_classes_in_file',
                message: `${classCount} class declarations found — only the first is mapped`,
                file:    fullPath,
            });
        }

        const info = extractClassInfo(content);
        if (!info) continue;

        const fullClass    = `${info.namespace}\\${info.className}`;
        const relativePath = path.relative(basePath, fullPath).split(path.sep).join('/');

        // ── Warning: duplicate class name ──
        if (classMap[fullClass]) {
            warnings.push({
                type:    'duplicate_class',
                message: `"${fullClass}" already mapped from ${classMap[fullClass]} — overwritten`,
                file:    fullPath,
            });
        }

        classMap[fullClass] = relativePath;
    }
}

// ─── Writer ──────────────────────────────────────────────────────────────────

function writeClassmapFile(classMap: ClassMap, outputPath: string): void {
    const entries = Object.entries(classMap)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([k, v]) => `    '${k}' => '${v}',`)
        .join('\n');

    const timestamp = new Date().toISOString();
    const php = [
        '<?php',
        `// Auto-generated by WP Classmap: Lightning Fast Autoloading — ${timestamp}`,
        '// Do not edit manually.',
        'return array(',
        entries,
        ');',
        '',
    ].join('\n');

    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    fs.writeFileSync(outputPath, php, 'utf8');
}

// ─── Public API ──────────────────────────────────────────────────────────────
export function generateClassmap(
    includesDir: string,
    outputFile:  string,
    exclude:     string[] = [],
): GenerateResult {
    const scanPath   = path.resolve(includesDir);
    const outputPath = path.resolve(outputFile);
    const outputDir  = path.dirname(outputPath);

    if (!fs.existsSync(scanPath)) {
        throw new Error(`Directory not found: ${scanPath}`);
    }

    // Merge user exclusions with defaults
    const excludeSet = new Set([...DEFAULT_EXCLUDE, ...exclude]);

    const classMap: ClassMap = {};
    const warnings: Warning[] = [];

    scanDir(scanPath, outputDir, classMap, outputPath, excludeSet, warnings);
    writeClassmapFile(classMap, outputPath);

    return {
        includesDir: path.basename(scanPath),
        count:       Object.keys(classMap).length,
        outputPath,
        warnings,
    };
}

export function generateAllClassmaps(
    directories: DirectoryConfig[],
): GenerateResult[] {
    return directories.map(({ includesDir, outputFile, exclude = [] }) => {
        try {
            return generateClassmap(includesDir, outputFile, exclude);
        } catch (err) {
            return {
                includesDir,
                count:      0,
                outputPath: outputFile,
                warnings:   [],
                error:      (err as Error).message,
            };
        }
    });
}